### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by gormster** [Vawlpe/MOLE#13]
After a bit of finagling, I've got Back.exe to build and run on macOS.

```sh
macbook-pro:Back gormster$ ./bin/Debug/Back
Settings: UPDATE_Asar = release
Dependency Update Sequence
Settings: UPDATE_Asar = build
Dependency Update Sequence
Asar Updated to build last modified at 7/10/2020 6:26:57 AM
```

To be honest - I'm not 100% sure what that means, but it seems like at least a fair chunk of the code works fine on macOS. I'll put up a branch on my fork in a bit with build instructions.

The binary is 21MB, which seems… kinda big? But not like, unreasonably big. And that's statically linked, no external dependency on mono.

**Comment by gormster** [comment]
https://github.com/gormster/MOLE/tree/macos

there's the changes. as you can see, no codebase changes, just build system stuff.

**Comment by Vawlpe** [comment]
thanks for the effort, multi-platform support trough mono is great, the output of  Back.exe is just an autoupdating test for Asar, and yes there is a way to get asar.dlyb copied to the output directory, add it to the project the same way asar.dll is, but said autoupdating systems may need to be modified, the Release version updating mode doesnt need much changing, just also extract the dylib file from the zip, unfortunately the Build mode is trickier as currently the dylib isn't part of the artifacts that get uploaded to the servers, @randomdude999 might be able to change it so it is also uploaded

**Comment by randomdude999** [comment]
@Vawlpe you mean the asar dylib? it is uploaded, the url is just like you'd expect, https://random.muncher.se/ftp/asar/osx/clang/libasar.dylib (or replace clang with gcc to get the variant that's compiled with gcc obviously)
though i'm pretty sure osx hates unsigned exes from the internet, so it probably won't run without checking a dozen checkboxes deep in some settings menu

**Comment by Vawlpe** [comment]
Ah thx, didnt realize everything was uploaded, imma dumm

**Comment by Vawlpe** [comment]
b1772e524b0de926615220f6e4479e99e12ffd97 Download/Update asar.dylib and asar.so for multiplatforming
