### ISSUE TITLE
Remove closed-source dependency lunarcompress.dll

### ISSUE THREAD

**Issue by gormster** [Vawlpe/MOLE#14]
LunarCompress is not open source, and MOLE can't really be cross-platform with a Windows-only DLL dependency. I've spent a few fruitless hours trying to get it to device-independent LLVM-IR, but no dice, and to be frank, it's kind of antithetical to the whole concept of MOLE as an open-source project.

So we probably need a sub-project that's an open-source replacement for those functions.

**Comment by Vawlpe** [comment]
Agreed, LC was a temporary solution as i was intending to manually recreate the necesarry functions but i just wanted a way to keep going with MOLE even without an open source implementation of Lunar Compress

**Comment by Vawlpe** [comment]
I belive we should just directly integrate useful LC funds directly into the ROM & GFX Handlers instead. 
For a start, the snes <-> pc address conversion functions I stuffed into Libs.asar.cs can be moved to the ROMhandler and they can even have an alternative where you don't need to pass the mapping mode and it just takes the ROMhandlers internal ROM type / mapping mode

Also you can find in some past commits there was and may still be palette color conversion functions and even a work in progress and sometimes almost complete decompression function for the GFX that can be restored and worked on. 

Unfortunately, as stated at the top of the README rightnow, I'm unable to work in any of this as my computer isn't working.

**Comment by Vawlpe** [comment]
24a83646ab4871ea482c9909578f70f4bee061c3
